# Jira Exporter Workflow
# Runs every hour or manually
# Uses GitHub secrets:
# PORT_CLIENT_ID, PORT_CLIENT_SECRET, ATLASSIAN_USER_EMAIL, ATLASSIAN_USER_TOKEN

on:
    workflow_dispatch:
    schedule:
        - cron: '0 */1 * * *'  # every hour

jobs:
    run-integration:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        
        steps:
            - name: Run Jira Integration
              uses: port-labs/ocean-sail@v1
              with:
                type: jira
                port_client_id: ${{ secrets.PORT_CLIENT_ID }}
                port_client_secret: ${{ secrets.PORT_CLIENT_SECRET }}
                port_base_url: "https://api.port.io"
                config: |
                    jira_host: "https://daviddaida95-1750231224272.atlassian.net"
                    atlassian_user_email: ${{ secrets.ATLASSIAN_USER_EMAIL }}
                    atlassian_user_token: ${{ secrets.ATLASSIAN_USER_TOKEN }}

